### ISSUE TITLE
Dockerfile for nginx not needed

### ISSUE THREAD

**Issue by pschaub** [jguyomard/docker-laravel#8]
The dockerfile for nginx is not needed.

Here is a full example how to use nginx without an own "Dockerfile for nginx":

```
version: '3'
services:

  # Application
  app:
    build:
      context: .
      dockerfile: ./.docker/app/app.dockerfile
    volumes:
      - codevolume:/var/www

  # Web server
  web:
    image: nginx
    volumes:
      - ./.docker/web/vhost.conf:/etc/nginx/conf.d/default.conf
      - codevolume:/var/www
    depends_on:
      - app
    ports:
      - 8080:80
      - 8443:443

volumes:
  codevolume:
```
_(This is just an example.)_
